name: dockerloginDEVQA

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  LogintodockerhubDEV:
    runs-on: ubuntu-latest
    environment: DEV
    steps:
    - uses: actions/checkout@v3
    - name: docker login
      uses: docker/login-action@v2.1.0
      with:
       username: ${{secrets.DOCKERHUBUSERNAME}}
       password: ${{secrets.DOCKERHUBPASSWORD}}
    - name: Docker Pull
      run: docker pull hello-world
    - name: Docker Tag
      run: docker tag hello-world abhijitacntraining3/dockerdemo
    - name: Docker Push
      run: docker push abhijitacntraining3/dockerdemo
  LogintodockerhubQA:
    runs-on: ubuntu-latest
    environment: QA
    steps:
    - uses: actions/checkout@v3
    - name: docker login
      uses: docker/login-action@v2.1.0
      with:
       username: ${{secrets.DOCKERHUBUSERNAME}}
       password: ${{secrets.DOCKERHUBPASSWORD}}
    - name: Docker Pull
      run: docker pull nginx
    - name: Docker Tag
      run: docker tag nginx abhijitacntraining3/dockerdemo
    - name: Docker Push
      run: docker push abhijitacntraining3/dockerdemo
